name: publish website
on:
    push:
      branches: 
        - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: publish
        run: ./publish_to_ghpages.sh


